In [48]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
from google.colab import files
d = files.upload()

Saving titanic.csv to titanic.csv


In [3]:
df = pd.read_csv('titanic.csv')

In [4]:
df.shape

(891, 12)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [6]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [7]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [8]:
df=df.drop(['PassengerId','Name', 'Ticket', 'Cabin'], axis = 1)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    object 
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64  
 5   Parch     891 non-null    int64  
 6   Fare      891 non-null    float64
 7   Embarked  889 non-null    object 
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB


In [10]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

In [11]:
df['Sex'] = le.fit_transform(df['Sex'])

In [12]:
df['Embarked'] = le.fit_transform(df['Embarked'])

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    int64  
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64  
 5   Parch     891 non-null    int64  
 6   Fare      891 non-null    float64
 7   Embarked  891 non-null    int64  
dtypes: float64(2), int64(6)
memory usage: 55.8 KB


In [14]:
df= df.dropna()

In [15]:
df.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [49]:
x =df.iloc[:,1:8]

In [50]:
x

Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         3    1  22.0      1      0   7.2500         2
1         1    0  38.0      1      0  71.2833         0
2         3    0  26.0      0      0   7.9250         2
3         1    0  35.0      1      0  53.1000         2
4         3    1  35.0      0      0   8.0500         2
..      ...  ...   ...    ...    ...      ...       ...
885       3    0  39.0      0      5  29.1250         1
886       2    1  27.0      0      0  13.0000         2
887       1    0  19.0      0      0  30.0000         2
889       1    1  26.0      0      0  30.0000         0
890       3    1  32.0      0      0   7.7500         1

[714 rows x 7 columns]

In [53]:
y = df.iloc[:,0]

In [54]:
y

0      0
1      1
2      1
3      1
4      0
      ..
885    0
886    0
887    1
889    1
890    0
Name: Survived, Length: 714, dtype: int64

In [55]:
from sklearn.model_selection import train_test_split

In [56]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2, random_state=345)

In [60]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report

In [61]:
model1 = KNeighborsClassifier(n_neighbors=5)

In [62]:
model1.fit(x_train,y_train)

KNeighborsClassifier()

In [63]:
ypredict1 = model1.predict(x_test)

In [64]:
y_test

687    0
187    1
872    0
74     1
416    1
      ..
569    1
432    1
245    0
520    1
765    1
Name: Survived, Length: 143, dtype: int64

In [65]:
ypredict1

array([0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1])

In [81]:
k_cm = confusion_matrix(y_test,ypredict1)

In [67]:
k_cm

array([[66, 17],
       [30, 30]])

In [68]:
model2 = SVC()

In [69]:
model2.fit(x_train, y_train)

SVC()

In [70]:
ypredict2 = model2.predict(x_test)

In [71]:
s_cm = confusion_matrix(y_test, ypredict2)

In [72]:
s_cm

array([[70, 13],
       [39, 21]])

In [73]:
model3 = LogisticRegression()

In [74]:
model3.fit(x_train,y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [75]:
ypredict3 = model3.predict(x_test)

In [82]:
l_cm = confusion_matrix(y_test,ypredict3)

In [77]:
l_cm

array([[69, 14],
       [20, 40]])

In [78]:
x1 = x.copy()

In [79]:
from sklearn import preprocessing
norm_x = preprocessing.normalize(x1)

In [80]:
x1_train,x1_test,y1_train,y1_test = train_test_split(norm_x,y,test_size=0.3, random_state=3)

In [83]:
model1.fit(x1_train,y1_train)

KNeighborsClassifier()

In [84]:
ypredict4 = model1.predict(x1_test)

In [85]:
k1_cm = confusion_matrix(y1_test,ypredict4)

In [86]:
k1_cm

array([[105,  25],
       [ 33,  52]])

In [87]:
model2.fit(x1_train, y1_train)

SVC()

In [88]:
ypredict5 = model2.predict(x1_test)

In [89]:
s1_cm = confusion_matrix(y1_test, ypredict5)

In [90]:
s1_cm

array([[108,  22],
       [ 45,  40]])

In [91]:
model3.fit(x1_train,y1_train)

LogisticRegression()

In [92]:
ypredict6 = model3.predict(x1_test)

In [93]:
l1_cm = confusion_matrix(y1_test,ypredict6)

In [94]:
l1_cm


array([[107,  23],
       [ 43,  42]])

In [95]:
x2 = x.copy()

In [96]:
x_l1norm = preprocessing.normalize(x2, norm='l1')

In [97]:
x3 = x.copy()

In [98]:
from sklearn.preprocessing import StandardScaler

In [99]:

std = StandardScaler()

In [100]:

x_std = std.fit_transform(x3)


In [101]:
x2_train,x2_test,y2_train,y2_test = train_test_split(x_l1norm,y,test_size=0.3, random_state=3)

In [102]:
model1.fit(x2_train,y2_train)

KNeighborsClassifier()

In [103]:
ypredict7 = model1.predict(x2_test)

In [104]:
k2_cm = confusion_matrix(y2_test,ypredict7)

In [105]:
k2_cm

array([[103,  27],
       [ 35,  50]])

In [106]:
model2.fit(x2_train, y2_train)

SVC()

In [107]:
ypredict8 = model2.predict(x2_test)

In [108]:
s2_cm = confusion_matrix(y2_test, ypredict8)
s2_cm

array([[109,  21],
       [ 46,  39]])

In [109]:
model3.fit(x2_train,y2_train)

LogisticRegression()

In [110]:
ypredict9 = model3.predict(x2_test)

In [112]:
l2_cm = confusion_matrix(y2_test,ypredict9)
l2_cm

array([[109,  21],
       [ 47,  38]])

In [113]:
x3_train,x3_test,y3_train,y3_test = train_test_split(x_std,y,test_size=0.3, random_state=345)

In [114]:
model1.fit(x3_train,y3_train)

KNeighborsClassifier()

In [115]:
ypredict10 = model1.predict(x3_test)

In [116]:
k3_cm = confusion_matrix(y3_test,ypredict10)

In [117]:
k3_cm

array([[106,  24],
       [ 26,  59]])

In [118]:
model2.fit(x3_train, y3_train)

SVC()

In [119]:
ypredict11 = model2.predict(x3_test)

In [120]:
s3_cm = confusion_matrix(y3_test, ypredict11)

In [121]:
s3_cm

array([[115,  15],
       [ 27,  58]])

In [122]:
model3.fit(x3_train,y3_train)

LogisticRegression()

In [123]:
ypredict12 = model3.predict(x3_test)

In [124]:
l3_cm = confusion_matrix(y3_test,ypredict12)
l3_cm

array([[107,  23],
       [ 26,  59]])

In [125]:
df1 = df.copy()

In [126]:
Q1 = df1['Age'].quantile(0.25)
Q3 = df1['Age'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
df1_filtered = df1[(df1['Age'] >= lower_bound) & (df1['Age'] <= upper_bound)]

In [128]:

Q1 = df1_filtered['Fare'].quantile(0.25)
Q3 = df1_filtered['Fare'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
df_filtered = df1_filtered[(df1_filtered['Fare'] >= lower_bound) & (df1_filtered['Fare'] <= upper_bound)]

In [129]:
x4 = df_filtered.iloc[:,1:8]
y1 = df_filtered.iloc[:,0]

In [130]:
x4_train,x4_test,y4_train,y4_test = train_test_split(x4,y1,test_size=0.3, random_state=345)


In [131]:
model1.fit(x4_train,y4_train)

KNeighborsClassifier()

In [132]:
ypredict13 = model1.predict(x4_test)

In [133]:
k4_cm = confusion_matrix(y4_test,ypredict13)
k4_cm

array([[90, 14],
       [48, 26]])

In [134]:
model2.fit(x4_train, y4_train)

SVC()

In [135]:
ypredict14 = model2.predict(x4_test)

In [137]:
s4_cm = confusion_matrix(y4_test, ypredict14)
s4_cm

array([[92, 12],
       [64, 10]])

In [138]:
model3.fit(x4_train,y4_train)

LogisticRegression()

In [139]:
ypredict15 = model3.predict(x4_test)

In [140]:
l4_cm = confusion_matrix(y4_test,ypredict15)
l4_cm


array([[100,   4],
       [ 37,  37]])