In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import RandomForestClassifier

In [2]:
from google.colab import files
d = files.upload()

Saving wine_data.csv to wine_data.csv


In [3]:
df = pd.read_csv('wine_data.csv')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21000 entries, 0 to 20999
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed_acidity         21000 non-null  float64
 1   volatile_acidity      21000 non-null  float64
 2   citric_acid           21000 non-null  float64
 3   residual_sugar        21000 non-null  float64
 4   chlorides             21000 non-null  float64
 5   free_sulfur_dioxide   21000 non-null  float64
 6   total_sulfur_dioxide  21000 non-null  float64
 7   density               21000 non-null  float64
 8   pH                    21000 non-null  float64
 9   sulphates             21000 non-null  float64
 10  alcohol               21000 non-null  float64
 11  quality               21000 non-null  int64  
dtypes: float64(11), int64(1)
memory usage: 1.9 MB


In [5]:
df.isnull().sum()

fixed_acidity           0
volatile_acidity        0
citric_acid             0
residual_sugar          0
chlorides               0
free_sulfur_dioxide     0
total_sulfur_dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [6]:
df

fixed_acidity  volatile_acidity  citric_acid  residual_sugar  \
0               11.6             0.580         0.66            2.20   
1               10.4             0.610         0.49            2.10   
2                7.4             1.185         0.00            4.25   
3               10.4             0.440         0.42            1.50   
4                8.3             1.020         0.02            3.40   
...              ...               ...          ...             ...   
20995            9.7             1.020         0.91           50.00   
20996           10.2             0.610         0.88           53.80   
20997           13.4             0.460         1.04           52.10   
20998            6.6             1.030         1.09           25.30   
20999            9.3             0.930         1.32           33.60   

       chlorides  free_sulfur_dioxide  total_sulfur_dioxide  density    pH  \
0          0.074                 10.0                  47.0  1.00080  3.25   
1          0.200                  5.0                  16.0  0.99940  3.16   
2          0.097                  5.0                  14.0  0.99660  3.63   
3          0.145                 34.0                  48.0  0.99832  3.38   
4          0.084                  6.0                  11.0  0.99892  3.48   
...          ...                  ...                   ...      ...   ...   
20995      0.412                114.6                 181.7  1.02085  3.30   
20996      0.250                 62.4                 204.7  1.02776  3.52   
20997      0.449                 63.0                 273.5  1.02618  2.89   
20998      0.138                179.8                 295.0  1.02476  2.94   
20999      0.412                128.7                 290.1  1.02182  3.16   

       sulphates  alcohol  quality  
0           0.57      9.0        3  
1           0.63      8.4        3  
2           0.54     10.7        3  
3           0.86      9.9        3  
4           0.49     11.0        3  
...          ...      ...      ...  
20995       0.89     12.0        9  
20996       1.14      9.7        9  
20997       1.76      9.3        9  
20998       1.54     12.9        9  
20999       1.42     13.0        9  

[21000 rows x 12 columns]

In [7]:
x = df.iloc[:,0:11]

In [8]:
y = df.iloc[:,-1]

In [9]:
x

fixed_acidity  volatile_acidity  citric_acid  residual_sugar  \
0               11.6             0.580         0.66            2.20   
1               10.4             0.610         0.49            2.10   
2                7.4             1.185         0.00            4.25   
3               10.4             0.440         0.42            1.50   
4                8.3             1.020         0.02            3.40   
...              ...               ...          ...             ...   
20995            9.7             1.020         0.91           50.00   
20996           10.2             0.610         0.88           53.80   
20997           13.4             0.460         1.04           52.10   
20998            6.6             1.030         1.09           25.30   
20999            9.3             0.930         1.32           33.60   

       chlorides  free_sulfur_dioxide  total_sulfur_dioxide  density    pH  \
0          0.074                 10.0                  47.0  1.00080  3.25   
1          0.200                  5.0                  16.0  0.99940  3.16   
2          0.097                  5.0                  14.0  0.99660  3.63   
3          0.145                 34.0                  48.0  0.99832  3.38   
4          0.084                  6.0                  11.0  0.99892  3.48   
...          ...                  ...                   ...      ...   ...   
20995      0.412                114.6                 181.7  1.02085  3.30   
20996      0.250                 62.4                 204.7  1.02776  3.52   
20997      0.449                 63.0                 273.5  1.02618  2.89   
20998      0.138                179.8                 295.0  1.02476  2.94   
20999      0.412                128.7                 290.1  1.02182  3.16   

       sulphates  alcohol  
0           0.57      9.0  
1           0.63      8.4  
2           0.54     10.7  
3           0.86      9.9  
4           0.49     11.0  
...          ...      ...  
20995       0.89     12.0  
20996       1.14      9.7  
20997       1.76      9.3  
20998       1.54     12.9  
20999       1.42     13.0  

[21000 rows x 11 columns]

In [10]:
from sklearn.decomposition import PCA

In [11]:
pca = PCA(n_components=5)

In [12]:
pca.fit(x)

PCA(n_components=5)

In [13]:
x_pca = pca.transform(x)

In [14]:
explained_variance = pca.explained_variance_ratio_

In [15]:
explained_variance

array([8.58033392e-01, 1.34970581e-01, 6.72576005e-03, 1.85890641e-04,
       7.15988772e-05])

In [16]:
x

fixed_acidity  volatile_acidity  citric_acid  residual_sugar  \
0               11.6             0.580         0.66            2.20   
1               10.4             0.610         0.49            2.10   
2                7.4             1.185         0.00            4.25   
3               10.4             0.440         0.42            1.50   
4                8.3             1.020         0.02            3.40   
...              ...               ...          ...             ...   
20995            9.7             1.020         0.91           50.00   
20996           10.2             0.610         0.88           53.80   
20997           13.4             0.460         1.04           52.10   
20998            6.6             1.030         1.09           25.30   
20999            9.3             0.930         1.32           33.60   

       chlorides  free_sulfur_dioxide  total_sulfur_dioxide  density    pH  \
0          0.074                 10.0                  47.0  1.00080  3.25   
1          0.200                  5.0                  16.0  0.99940  3.16   
2          0.097                  5.0                  14.0  0.99660  3.63   
3          0.145                 34.0                  48.0  0.99832  3.38   
4          0.084                  6.0                  11.0  0.99892  3.48   
...          ...                  ...                   ...      ...   ...   
20995      0.412                114.6                 181.7  1.02085  3.30   
20996      0.250                 62.4                 204.7  1.02776  3.52   
20997      0.449                 63.0                 273.5  1.02618  2.89   
20998      0.138                179.8                 295.0  1.02476  2.94   
20999      0.412                128.7                 290.1  1.02182  3.16   

       sulphates  alcohol  
0           0.57      9.0  
1           0.63      8.4  
2           0.54     10.7  
3           0.86      9.9  
4           0.49     11.0  
...          ...      ...  
20995       0.89     12.0  
20996       1.14      9.7  
20997       1.76      9.3  
20998       1.54     12.9  
20999       1.42     13.0  

[21000 rows x 11 columns]

In [17]:
x_pca

array([[-2.19529921e+02,  5.76203887e+00, -1.66516127e-01,
         4.57922564e+00, -9.26086779e-01],
       [-2.47622993e+02,  1.95248726e+01,  2.57358066e+00,
         3.46261206e+00, -1.55844378e+00],
       [-2.48995056e+02,  2.07674263e+01,  4.70798987e+00,
         1.01096776e-01,  3.63156741e-01],
       ...,
       [ 1.44987122e+00, -7.84482856e+01,  2.59170119e+01,
         3.62388146e+00, -1.78130339e+00],
       [ 8.13666611e+01,  2.60698837e+00, -1.72861449e+01,
        -3.49176614e+00,  1.09136802e+00],
       [ 4.96215765e+01, -3.56651325e+01, -2.09638957e+00,
        -6.57454090e-01,  1.50180727e+00]])

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
X_train, X_test, y_train, y_test = train_test_split(x_pca, y, test_size=0.2, random_state=42)

In [22]:
rf = RandomForestClassifier(n_estimators=100, random_state=42, criterion="entropy")

In [25]:
rf.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', random_state=42)

In [26]:
y_pred = rf.predict(X_test)

In [32]:
from sklearn.metrics import confusion_matrix, classification_report
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[372  59   5   2  17  52  59]
 [ 68 371  24  18  25  52  69]
 [ 43  31 335 132  17  24  39]
 [  5  10 113 391  46   5  10]
 [ 67  50  12  85 297  53  61]
 [ 55  55   7  16  36 374  65]
 [ 51  59   5   2  18  60 378]]


In [33]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           3       0.56      0.66      0.61       566
           4       0.58      0.59      0.59       627
           5       0.67      0.54      0.60       621
           6       0.61      0.67      0.64       580
           7       0.65      0.48      0.55       625
           8       0.60      0.62      0.61       608
           9       0.56      0.66      0.60       573

    accuracy                           0.60      4200
   macro avg       0.60      0.60      0.60      4200
weighted avg       0.61      0.60      0.60      4200

