In [1]:
import pandas as pd
import numpy as np
import io
from google.colab import files
uploaded = files.upload()


Saving 01Students.csv to 01Students.csv


In [2]:

df = pd.read_csv('01Students.csv')

In [3]:
df

Hours  Marks
0       0     34
1       1     36
2       1     33
3       1     39
4       1     42
5       2     45
6       2     38
7       3     45
8       3     53
9       3     46
10      3     56
11      4     59
12      4     55
13      4     56
14      5     72
15      5     59
16      6     62
17      6     71
18      7     78
19      7     88
20      7     61
21      7     74
22      8     71
23      8     89
24      9     82
25      9     67
26      9     89
27     10     81
28     10     82
29     11     79

In [4]:
df

Hours  Marks
0       0     34
1       1     36
2       1     33
3       1     39
4       1     42
5       2     45
6       2     38
7       3     45
8       3     53
9       3     46
10      3     56
11      4     59
12      4     55
13      4     56
14      5     72
15      5     59
16      6     62
17      6     71
18      7     78
19      7     88
20      7     61
21      7     74
22      8     71
23      8     89
24      9     82
25      9     67
26      9     89
27     10     81
28     10     82
29     11     79

In [5]:
df.head()

Hours  Marks
0      0     34
1      1     36
2      1     33
3      1     39
4      1     42

In [7]:
df.tail()

Hours  Marks
25      9     67
26      9     89
27     10     81
28     10     82
29     11     79

In [8]:
df.iloc[20:25]

Hours  Marks
20      7     61
21      7     74
22      8     71
23      8     89
24      9     82

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Hours   30 non-null     int64
 1   Marks   30 non-null     int64
dtypes: int64(2)
memory usage: 608.0 bytes


In [10]:
df.describe()

Hours      Marks
count  30.000000  30.000000
mean    5.200000  61.400000
std     3.188341  17.734828
min     0.000000  33.000000
25%     3.000000  45.250000
50%     5.000000  60.000000
75%     7.750000  77.000000
max    11.000000  89.000000

In [11]:
x = df[['Hours']]

In [12]:
x

Hours
0       0
1       1
2       1
3       1
4       1
5       2
6       2
7       3
8       3
9       3
10      3
11      4
12      4
13      4
14      5
15      5
16      6
17      6
18      7
19      7
20      7
21      7
22      8
23      8
24      9
25      9
26      9
27     10
28     10
29     11

In [13]:
y = df[['Marks']]

In [14]:
y

Marks
0      34
1      36
2      33
3      39
4      42
5      45
6      38
7      45
8      53
9      46
10     56
11     59
12     55
13     56
14     72
15     59
16     62
17     71
18     78
19     88
20     61
21     74
22     71
23     89
24     82
25     67
26     89
27     81
28     82
29     79

In [15]:
from sklearn.model_selection import train_test_split


In [17]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2, random_state=17)


In [18]:
from sklearn.linear_model import LinearRegression


In [19]:
lr = LinearRegression()

In [20]:
lr.fit(x_train, y_train)

LinearRegression()

In [21]:
y_predict = lr.predict(x_test)

In [22]:
y_predict

array([[35.05041436],
       [69.05455801],
       [69.05455801],
       [54.48135359],
       [44.76588398],
       [73.91229282]])

In [23]:
error = y_test - y_predict

In [24]:
error

Marks
0   -1.050414
18   8.945442
21   4.945442
11   4.518646
5    0.234116
23  15.087707

In [25]:
from sklearn.preprocessing import PolynomialFeatures

In [26]:
poly = PolynomialFeatures(degree=2)

In [27]:
x_poly = poly.fit_transform(x_train)

In [28]:
x_poly

array([[  1.,  10., 100.],
       [  1.,   7.,  49.],
       [  1.,   9.,  81.],
       [  1.,   9.,  81.],
       [  1.,   1.,   1.],
       [  1.,   1.,   1.],
       [  1.,   3.,   9.],
       [  1.,   3.,   9.],
       [  1.,   3.,   9.],
       [  1.,  10., 100.],
       [  1.,   5.,  25.],
       [  1.,   1.,   1.],
       [  1.,   7.,  49.],
       [  1.,   4.,  16.],
       [  1.,   3.,   9.],
       [  1.,   1.,   1.],
       [  1.,   9.,  81.],
       [  1.,   4.,  16.],
       [  1.,   6.,  36.],
       [  1.,   8.,  64.],
       [  1.,   2.,   4.],
       [  1.,  11., 121.],
       [  1.,   6.,  36.],
       [  1.,   5.,  25.]])

In [30]:
lr.fit(x_poly,y_train)

LinearRegression()

In [31]:
result2 = poly.transform(x_test)

In [32]:
y_predict2 = lr.predict(result2)

In [33]:
y_predict2

array([[27.51869807],
       [71.94298616],
       [71.94298616],
       [57.09483117],
       [43.70370649],
       [75.49542929]])

In [34]:
error2 = y_test - y_predict2

In [36]:
error2

Marks
0    6.481302
18   6.057014
21   2.057014
11   1.905169
5    1.296294
23  13.504571

In [37]:
error

Marks
0   -1.050414
18   8.945442
21   4.945442
11   4.518646
5    0.234116
23  15.087707